### ISSUE TITLE
SQLiteCantOpenDatabaseException:

### ISSUE THREAD

**Issue by cukelty** [yxl/DownloadProvider#20]
```
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
	at com.mozillaonline.providers.downloads.DownloadProvider.update(DownloadProvider.java:925)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:355)
	at android.content.ContentResolver.update(ContentResolver.java:1365)
	at com.mozillaonline.providers.downloads.DownloadThread.notifyThroughDatabase(DownloadThread.java:832)
	at com.mozillaonline.providers.downloads.DownloadThread.notifyDownloadCompleted(DownloadThread.java:807)
	at com.mozillaonline.providers.downloads.DownloadThread.run(DownloadThread.java:202)
```

**Comment by cukelty** [comment]
how can  i  resulve this
